#!name=💛 Locket Gold 
#!desc=Unlocked Locket with all function
#!tele=https://t.me/miss_lanho

[Script]
revenuecat = type=http-response, pattern=^https:\/\/api\.revenuecat\.com\/.+\/(receipts$|subscribers\/[^/]+$), script-path=https://raw.githubusercontent.com/miss-lanho/locket-gold/refs/heads/main/module/js/locket.js, requires-body=true, max-size=-1, timeout=60

deleteHeader = type=http-request, pattern=^https:\/\/api\.revenuecat\.com\/.+\/(receipts|subscribers), script-path=https://raw.githubusercontent.com/miss-lanho/locket-gold/refs/heads/main/module/js/deleteHeader.js, timeout=60

[MITM]
hostname = %APPEND% api.revenuecat.com
